### ISSUE TITLE
[IPFS] Unable to fetch metadata in remote

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist-subsquid#101]
A strange issue has been encountered while fetching metadata via IPFS for marketId `31` indexed at block `31070`.
At one of the remote hosts, no data is received and the processor remains stuck at this point. 

However, while reproducing the issue at local and the other host: things seem to work fine.

**Comment by saboonikhil** [comment]
The processor resumed after putting a simple check to omit metadata for the above mentioned market. Your suggestion worked @sea212 - if this was the metadata which created trouble for frontend, it hurts subsquid as well.

**Comment by sea212** [comment]
I just tried to fetch the data using my ipfs client and ipfs.io and it took quite a while, more than a minute. Eventually it was able to fetch it. You can see the data at [ipfs.io](http://192.168.0.91:8080/ipfs/f01551530fa0bb52e67d0d9f89bf26552e1b27b76c1070737c9b2416a9cd174509e3bd424bd353dda3c1245cde69a61efddc62574)
Not sure what happened, best guess is that the ipfs data fetch instruction used within SubSquid just timed out because it took too long.
Improving the IPFS infastructure is on the priority list, this will improve fetch speeds in the future (alongside with availability)
