### ISSUE TITLE
Dev network has balances too large to process

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist-subsquid#116]
Development network balances are 2,126.7647 YDEV (Yotta) units, that cause error when processing data with the subsquid:

```
Error: Number can only safely store up to 53 bits.
```

@sea212 @saboonikhil 
Not sure what's the best solution for this, maybe set lower balances for dev network inside substrate repository, or change schema type for `pvalue` from `Float` to `BigInt`.

Right now dev network cannot be used with subsquid because of this afaik.

**Comment by saboonikhil** [comment]
@TvrtkoM, If `pvalue` is updated to `BigInt` we would get `RangeError: The number 10151897124.242424 cannot be converted to a BigInt because it is not an integer`. 

If we forcefully satisfy `Float`, we would get exponential result like `2.1267647932558654e+37`.

There are two options right now - Either utilise the above result or convert `pvalue` to `String`.

Note: `pvalue` is actually a temporary field, it would be removed once resolvers are in place for obtaining portfolio metrics.

Also, since we are talking about balances, a question which comes into my mind right now is "What is the chance of  actual balances going more than 53 bits?" @sea212 @maltekliemann

**Comment by saboonikhil** [comment]
@TvrtkoM,  if `pvalue` is updated to `BigInt` we would get 
```
RangeError: The number 10151897124.242424 cannot be converted to a BigInt because it is not an integer.
```
The error `Error: Number can only safely store up to 53 bits` is due to the usage of the method `toNumber()` which allows javascript number upto 53 bits. However, `Number()` converts it to an object that represents a number of any kind supporting javascript 64-bit floating-point numbers. 

Is it ok if it is represented as an exponential result like `2.1267647932558654e+37`? `pvalue` is actually a temporary field, it would be removed once resolvers are in place for obtaining portfolio metrics.

Also, since we are talking about balances, a question which comes into my mind right now is "What is the chance of actual balances going more than 53 bits?" @sea212 @maltekliemann

**Comment by saboonikhil** [comment]
@TvrtkoM,  if `pvalue` is updated to `BigInt` we would get 
```
RangeError: The number 10151897124.242424 cannot be converted to a BigInt because it is not an integer.
```
The error `Error: Number can only safely store up to 53 bits` is due to the usage of the method `toNumber()` which allows javascript number upto 53 bits. However, `Number()` converts it to an object that represents a number of any kind supporting javascript 64-bit floating-point numbers. 

Is it ok if it is represented as an exponential result like `2.1267647932558654e+37`? `pvalue` is actually a temporary field, it would be removed once resolvers are in place for obtaining portfolio metrics.
