### ISSUE TITLE
Pool accountId is wrong on one maybe more pools.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/zeitgeist-subsquid#240]
The indexed value for `accountId` on pool with pool id `66` is `dE1VdxVn8xy7HFH9dLfBXwVzRx15pixS7xb9ZE5aaZ6UaekrJ` and this has no balances for the assets in this pool resulting in an error when doing lookup.

But calling the `swaps_getPoolAccountId` rpc method for pool `66` gives the account address `dE1VdxVn8xy7HFNWfF1jucr9ndHhDfD2QxAG8TtYWN69USj4P`, which seems to be the correct account id for this pool and gives the correct balances when doing lookup.

**Comment by saboonikhil** [comment]
Just finished investigating this issue. Thank you for bringing this up!

The account lookup for mapping with the pool needs to be refined. There is an error due to the presence of multiple `system.NewAccount` events in the same block.

https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/21718bbfd7a3b3650b496acffff522a814b60b5c/src/mappings/swaps/index.ts#L59-L60
