### ISSUE TITLE
Scalar asset price goes to zero once resolved

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#258]
See data for this market: https://app.zeitgeist.pm/markets/36

Would expect similar behaviour to categorical markets where the assets go to their resolved prices

**Comment by saboonikhil** [comment]
Yep, need to work on scalar markets. Thanks for highlighting!

**Comment by saboonikhil** [comment]
Regarding this particular market, the prices are correct since `resolvedOutcome` matches with the lowerScalarBound leading `Short` token going to 1 and `Long` to 0.

![Screenshot 2023-01-19 at 4 55 28 PM](https://user-images.githubusercontent.com/36529278/213430493-a15281c6-0c12-41be-b3e7-0b456102bfa8.png)
