### ISSUE TITLE
Market participants

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#284]
We need a way to efficiently get market participants to display on a market card. Ideally we would be able to get this information along with the `market` or `pool`

**Comment by saboonikhil** [comment]
Resolvers seemed to be an option but it looks like subsquid uses them as an extension for creating fresh queries and schema. Amending existing structure isn't yet possible, therefore we would have to do an extra query (per market basis) on `HistoricalAsset` for pulling number of participants.

In order to avoid computation on the client side and pick distinct records, resolver can be used as a means to provide this value. Further, it can be optimised to accept a range of market-ids.
