### ISSUE TITLE
Process & map market events

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist-subsquid#6]
The following events are being processed: https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/prediction-markets/src/lib.rs#L1269-L1291

**Comment by saboonikhil** [comment]
@sea212 After reviewing all the market events, I have few queries:
- `MarketResolvedEvent` is not being emitted. Am I correct here?
- Info for few markets (eg. 1,9,21) are not being fetched via `api.query.marketCommons.markets(marketId)` 
- Does the market status changes to `Resolved` with non-null `outcomeReport`?

**Comment by sea212** [comment]
1. The event is not emitted currently, but will be [once runtime v0.2.2 is deployed](https://github.com/zeitgeistpm/zeitgeist/pull/415/files#diff-f5399e482d98142f978aa63b3dbf82e342f9ddd7bd31c4aa3c1c28c26b83d743R1740-R1744)
2. Thanks, I'll have a look at that an report back.
3. For CPMM markets it should, unless it is an advised market that is rejected or there is a bug. For Rikiddo markets it is likewise, with the addition that they are discarded if not enough subsidy is gathered.

**Comment by TvrtkoM** [comment]
@sea212 - regarding point no. 2. There are markets that have been destroyed with sudo account during beta launch. Market ids of this markets are 9, 10, 11, 12, 42, 50.

Can this `MarketDestroy` event be used for (non)indexing with subsquid? We can probably filter them out for now in sdk, but since market can be created without metadata, it's not possible to distinguish such markets from the ones that are destroyed.

**Comment by saboonikhil** [comment]
The market data is in well sync with the chain and being fully utilised by the app.
